'use strict';
// WorldForge - exports the vault as a static wiki website (real HTML pages you can
// host free on GitHub Pages / Netlify / Cloudflare Pages, or just open locally).

const fs = require('fs');
const path = require('path');
const { renderMarkdown, slugFor, esc } = require('./md');

function write(p, content) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}

const CSS = String.raw`
:root { --bg:#0d1117; --panel:#161b22; --border:#2d333b; --text:#dce3ea; --muted:#8b949e; --accent:#58a6ff; --wl:#79c0ff; }
* { box-sizing: border-box; }
body { margin:0; font-family: 'Segoe UI', system-ui, sans-serif; background:var(--bg); color:var(--text); line-height:1.6; }
a { color: var(--accent); text-decoration:none; }
a:hover { text-decoration:underline; }
.layout { display:flex; min-height:100vh; }
.sidebar { width:280px; min-width:280px; background:var(--panel); border-right:1px solid var(--border); padding:16px; overflow-y:auto; max-height:100vh; position:sticky; top:0; }
.sidebar h1 { font-size:18px; margin:0 0 12px; }
.sidebar .sub { color:var(--muted); font-size:12px; margin-bottom:14px; }
.sidebar a.side { display:block; padding:4px 8px; border-radius:6px; color:var(--text); font-size:14px; }
.sidebar a.side:hover { background:#21262d; text-decoration:none; }
.sidebar a.side.active { background:#1f6feb33; color:var(--wl); }
.search { width:100%; padding:7px 10px; margin-bottom:12px; background:#0d1117; border:1px solid var(--border); border-radius:6px; color:var(--text); font-size:13px; }
.content { flex:1; padding:28px 36px; max-width:980px; }
.content h1 { margin-top:0; }
.crumb { color:var(--muted); font-size:13px; margin-bottom:6px; }
.tags { margin:10px 0 4px; }
.tagref { display:inline-block; background:#1f6feb22; color:var(--wl); border:1px solid #1f6feb55; padding:1px 8px; border-radius:99px; font-size:12px; margin-right:6px; text-decoration:none; }
.tagref:hover { text-decoration:none; background:#1f6feb44; }
.wl { color:var(--wl); }
.wl.missing { color:#f85149; opacity:.75; border-bottom:1px dashed #f8514966; }
blockquote { border-left:3px solid var(--accent); margin:10px 0; padding:4px 14px; color:var(--muted); background:#161b2255; }
pre { background:#0a0d12; border:1px solid var(--border); border-radius:8px; padding:12px; overflow-x:auto; font-size:13px; }
code { font-family: Consolas, monospace; font-size:.92em; }
code.inline { background:#21262d; padding:2px 6px; border-radius:5px; }
table { border-collapse: collapse; width:100%; margin:12px 0; }
th, td { border:1px solid var(--border); padding:6px 10px; text-align:left; }
th { background:var(--panel); }
.backlinks { margin-top:28px; border-top:1px solid var(--border); padding-top:14px; }
.backlinks h3 { margin:0 0 8px; font-size:14px; color:var(--muted); text-transform:uppercase; letter-spacing:.05em; }
.backlinks a { display:inline-block; margin:0 10px 6px 0; }
.rel { margin-top:26px; border-top:1px solid var(--border); padding-top:14px; }
.rel h3 { margin:0 0 8px; font-size:14px; color:var(--muted); text-transform:uppercase; letter-spacing:.05em; }
.footer { color:var(--muted); font-size:12px; margin-top:36px; }
`;

function pageShell(title, body, sidebarHtml, cssHref) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<link rel="stylesheet" href="${cssHref}">
</head>
<body>
<div class="layout">
<nav class="sidebar">${sidebarHtml}</nav>
<main class="content">${body}
<div class="footer">Generated by WorldForge</div>
</main>
</div>
</body>
</html>`;
}

function sideLink(href, label, active) {
  return `<a class="side${active ? ' active' : ''}" href="${href}">${esc(label)}</a>`;
}

function exportSite(vault, outDir, opts) {
  opts = opts || {};
  const notes = vault.notes;
  const byId = vault.notesById;

  // Precompute page hrefs for every note (relative, flat directory of page-*.html).
  const hrefOf = new Map();
  for (const n of notes) hrefOf.set(n.id, slugFor(n.title, true));

  const linkFor = (target, exists) => {
    if (!exists) return '#';
    const r = vault.resolve(target);
    return r ? hrefOf.get(r.id) : '#';
  };

  // Sidebar: all notes (flat, sorted), collapsible enough for simple use.
  const sidebarHtml = `<form onsubmit="return false"><input class="search" id="wf-search" placeholder="Filter notes..." autocomplete="off"></form><div id="side-links">` +
    notes.map(n => sideLink(hrefOf.get(n.id), n.title, false)).join('') +
    `</div><p class="sub"><a href="index.html">Home</a> &middot; <a href="graph.html">Graph</a></p>`;

  const usedSlugs = new Map();
  const pageFiles = [];
  for (const n of notes) {
    let slug = slugFor(n.title, true);
    if (usedSlugs.has(slug)) {
      let k = 2, s2;
      do { s2 = slug.replace(/\.html$/, '-' + k + '.html'); k++; } while (usedSlugs.has(s2));
      slug = s2;
      hrefOf.set(n.id, slug);
    }
    usedSlugs.set(slug, n.id);
    pageFiles.push({ note: n, slug });
  }

  // Tag pages
  const tagPages = new Map();
  for (const [tag, set] of vault.tagIndex) tagPages.set(tag, [...set]);

  const tagIndexHtml = pageShell(
    'Tags',
    `<h1>Tags</h1>` +
    [...vault.tagIndex.keys()].sort().map(t => {
      const count = vault.tagIndex.get(t).size;
      return `<a class="tagref" href="tag-${t.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.html">#${esc(t)}</a> <span style="color:var(--muted)">(${count})</span><br>`;
    }).join(''),
    sidebarHtml, 'wiki.css'
  );

  for (const [tag, ids] of tagPages) {
    const items = ids.sort().map(id => {
      const n = byId.get(id);
      return sideLink(hrefOf.get(id), n.title, false);
    }).join('');
    write(path.join(outDir, `tag-${tag.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.html`),
      pageShell('#' + tag, `<h1>Tag: #${esc(tag)}</h1>` + items, sidebarHtml, 'wiki.css'));
  }

  // Note pages
  for (const { note, slug } of pageFiles) {
    const html = renderMarkdown(note.body, (t) => !!vault.resolve(t), linkFor);
    const tagsHtml = note.tags.length ? `<div class="tags">${note.tags.map(t => `<a class="tagref" href="tag-${t.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.html">#${esc(t)}</a>`).join('')}</div>` : '';
    const backlinks = note.backlinks.length
      ? `<div class="backlinks"><h3>Backlinks</h3>${[...new Set(note.backlinks)].map(id => `<a href="${hrefOf.get(id)}">${esc(byId.get(id).title)}</a>`).join('')}</div>`
      : '';
    const outgoing = note.outgoing.length
      ? `<div class="rel"><h3>Outgoing links</h3>${[...new Set(note.outgoing)].map(id => `<a href="${hrefOf.get(id)}">${esc(byId.get(id).title)}</a>`).join('')}</div>`
      : '';
    write(path.join(outDir, slug),
      pageShell(note.title, `<div class="crumb">${esc(note.dir === '.' ? '' : note.dir)}</div><h1>${esc(note.title)}</h1>${tagsHtml}${html}${backlinks}${outgoing}`, sidebarHtml, 'wiki.css'));
  }

  // graph.html: full-screen 3D graph, self-contained.
  const graphData = JSON.stringify(vault.graph).replace(/</g, '\\u003c');
  write(path.join(outDir, 'graph.html'), `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Graph</title><link rel="stylesheet" href="wiki.css">
<style> html,body{margin:0;height:100%;} #wrap{position:fixed;inset:0;} .hud{position:fixed;top:10px;left:10px;z-index:5;background:#161b22ee;border:1px solid #2d333b;border-radius:8px;padding:8px 12px;font:13px 'Segoe UI',sans-serif;color:#dce3ea;}
 .hud input{background:#0d1117;border:1px solid #2d333b;color:#dce3ea;border-radius:6px;padding:5px 8px;margin-right:8px;}
 .hud a{color:#58a6ff;margin-left:8px;} #tip{position:fixed;pointer-events:none;background:#161b22ee;border:1px solid #2d333b;padding:4px 8px;border-radius:6px;font:12px 'Segoe UI',sans-serif;color:#dce3ea;display:none;z-index:6;}
 #loading{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;color:#8b949e;font:14px 'Segoe UI',sans-serif;}
</style></head>
<body><div id="wrap"></div>
<div class="hud"><input id="q" placeholder="Search notes..."><button id="go">Go</button><a href="index.html">Home</a></div>
<div id="tip"></div>
<div id="loading">Loading graph…</div>
<script src="three.min.js"></script>
<script src="graph-common.js"></script>
<script>
const DATA = ${graphData};
Graph3D.mount('wrap', DATA, { label: n => n.title, onOpen: n => { location.href = hrefOf[n.id] || 'index.html'; } });
const hrefOf = {};
${notes.map(n => `hrefOf[${JSON.stringify(n.id)}]=${JSON.stringify(hrefOf.get(n.id))};`).join('\n')}
document.getElementById('loading').remove();
document.getElementById('go').onclick = () => {
  const q = document.getElementById('q').value.toLowerCase();
  const hit = Object.keys(hrefOf).find(id => id.toLowerCase().includes(q));
  if (hit) location.href = hrefOf[hit];
};
</script></body></html>`);

  // index.html: home page with tag cloud + list of all notes.
  const allNotes = notes.map(n => sideLink(hrefOf.get(n.id), n.title, false)).join('');
  const tagCloud = [...vault.tagIndex.keys()].sort().map(t =>
    `<a class="tagref" href="tag-${t.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.html">#${esc(t)}</a>`).join(' ');
  write(path.join(outDir, 'index.html'), pageShell('Wiki',
    `<h1>Wiki</h1><p>${notes.length} notes &middot; ${vault.graph.links.length} links &middot; <a href="graph.html">Open 3D graph</a></p>
     <h2>Tags</h2><div>${tagCloud || '<i>none</i>'}</div><h2>All notes</h2>` + allNotes, sidebarHtml, 'wiki.css'));

  // graph-common.js + three.min.js copied by caller (server.js) into outDir.
  return { pages: notes.length + tagPages.size + 3, outDir };
}

module.exports = { exportSite, CSS };
